### ISSUE TITLE
post mock不成功

### ISSUE THREAD

**Issue by wanghui5257** [tianxiangbing/mock#1]
post mock 不成功，get的可以，为啥

**Comment by tianxiangbing** [comment]
@wanghui5257  可以的啊，不然你下载这个版本的？ https://github.com/tianxiangbing/icestar
下载地址：https://github.com/tianxiangbing/icestar/releases/download/2.0.10/icestar.exe

**Comment by wanghui5257** [comment]
不好意思，我这里弄错了，搞定了，多谢

田想兵 <notifications@github.com> 于2018年12月7日周五 下午6:09写道：
